const COLORS = {
  TURQOISE: "#5ACCCC",
  WHITE: "#FFFFFF",
  STEALBLUE: "#335C6E",
  YELLOW: "#FABD33",
  TURQOISE_LIGHT: "#CFFAFFA",
  ORANGE_RED: "#F76434",
  TEAL: "#4AA088",
  YELLOW_DARK: "#FAAD00",
  TURQOISE_DARK1: "#53C2C2",
  ORANGE_PASTEL: "#FFE6DC",
  TURQOISE_DARK2: "#28B8B8",
  LIGHT_GRAY: "#9DA9AA",
};

export default COLORS;
